name: Update Leaderboard

on:
  pull_request:
    types: [closed]
    branches:
      - 'week*'
      - 'Week*'
      - 'day*'
      - 'Day*'
  workflow_dispatch:

jobs:
  update-leaderboard:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          ref: main  # Always update leaderboard on main branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==2.1.1
          pip install pandas==2.2.0
          pip install numpy  # Required for pandas
          pip install tabulate==0.9.0
          pip install pytz==2024.1
          pip install python-dateutil==2.8.2

      - name: Update Leaderboard
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python .github/scripts/update_leaderboard.py

      - name: Commit and Push Leaderboard
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add LEADERBOARD.md
          git commit -m "Update leaderboard" || echo "No changes to commit"
          git push 