name: Weekly Challenge Reminders

on:
  schedule:
    # Runs every Monday at 9:00 AM EAT (06:00 UTC)
    - cron: '0 6 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Using a more stable Python version
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install packages one by one to handle any installation issues
          pip install PyGithub==2.1.1
          pip install pytz==2024.1
          pip install python-dateutil==2.8.2
          pip install --no-deps pandas==2.2.0
          pip install numpy  # Required for pandas
          pip install tabulate==0.9.0
          pip freeze

      - name: Create Weekly Reminder
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python .github/scripts/create_reminder.py || echo "Failed to create reminder, check script output above" 